name: note_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  moor: ^4.3.0
  fpdart: ^0.3.0
  avatar_glow: ^2.0.2
  html_editor_enhanced: ^2.5.1
  camera: ^0.10.5+2
  permission_handler: ^10.4.0
  google_mlkit_text_recognition: ^0.8.1
  intl: ^0.17.0
  image_picker: ^0.8.4+4
  cupertino_icons: ^1.0.2
  speech_to_text: ^6.2.0
  flutter_html: ^2.2.1 
  html: ^0.15.4
  html_unescape: ^2.0.0
  geolocator: ^7.7.0
  flutter_map: ^2.2.0
  latlng: ^1.0.0

  sqflite: ^2.2.2
  path: ^1.8.2

dev_dependencies:
    flutter_lints: ^2.0.0



flutter:
  uses-material-design: true
